name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change to master if your default branch is master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter build web --base-href "/yummy-flutter/"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages